version: "3.9"
services: 
 django_todo_app:
  container_name: "django-todo-app"
  build : .
  ports:
    - 8000:8000
  volumes:
    - django_todo_volume:/app
 mysql_db:
  container_name: "django-mysql-db"
  image: mysql:5.7
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: "test@123"
volumes:
 django_todo_volume:
